### ISSUE TITLE
App Settings does not update 

### ISSUE THREAD

**Issue by oalsing** [apals/FairManager#81]
Återskapa:

Gå till app settings, uppdatera vilka views som ska visas. Tryck på spara. Detta bör fungera (kolla api/settings/).

Klicka sedan i exempelvis att någon modul skall läggas till eller tas bort och tryck på spara. Kolla nu api. Oftast så uppdateras det inte!

**Comment by apals** [comment]
https://github.com/apals/FairManager/pull/82
